### PR TITLE
Send_fleet with moon

### PR DESCRIPTION
**Pull request by YOLOP0wn**
You have deleted my issue so i answer you here.

To take moon into send_fleet function , i have added "type" argument like this in init file:

```py
def send_fleet(self, planet_id, ships, speed, where, mission, type, resources):
        def get_hidden_fields(html):
            soup = BeautifulSoup(html, 'lxml')
            inputs = soup.findAll('input', {'type': 'hidden'})
            fields = {}
            for input_element in inputs:
                name = input_element.get('name')
                value = input_element.get('value')
                fields[name] = value
            return fields

        url = self.get_url('fleet1', {'cp': planet_id})

        res = self.session.get(url).content
        if not self.is_logged(res):
            raise NOT_LOGGED
        payload = {}
        payload.update(get_hidden_fields(res))
        for name, value in ships:
            payload['am%s' % name] = value
        res = self.session.post(self.get_url('fleet2'), data=payload).content

        payload = {}
        payload.update(get_hidden_fields(res))
        payload.update({'speed': speed,
                        'galaxy': where.get('galaxy'),
                        'system': where.get('system'),
                        'position': where.get('position'),
                        'type': type })
                        ....
                        ....
```

And in my script i created a function "move_fleet" who take may argument : 

```py
def move_fleet(planet_to_escape, planet_safe, planet_safe_name):
    my_resources = ogame.get_resources(planet_to_escape)
    ....
    ....
    ....
    type = 1
    if planet_safe_name == 'Lune':
        type = 3
    ogame.send_fleet(planet_to_escape, ships, speed, planet_safe, mission, type, resources)
```

Where planet_safe is the "where" coord for send_fleet() function, and planet_safe_name to check if its the name of your moon, so if planet_safe_name == moon then : 

type = 1
    if planet_safe_name == 'Lune':
        type = 3
    ogame.send_fleet(planet_to_escape, ships, speed, planet_safe, mission, type, resources)

Guys, i will play on the next universe, (think it will come early june 1-5), i suggest to play all together :)

### CODE REVIEW

**Comment by alaingilbert** [comment]
You have deleted my issue so i answer you here.
Wait what ?! [you closed it !](https://github.com/alaingilbert/pyogame/issues/26#event-1097709479)

I see thanks for the infos.

**Comment by YOLOP0wn** [comment]
i saw you did many commit, good :) 
but it seems that the bot is now spotted by gameforge, i think they spot the get request on json api.

**Comment by alaingilbert** [comment]
I don't think any of these commits changed the way the bot would be detected or not.
What makes you say that ?
By the way, I heard that there is two main ways that they can detect a bot:
- If you keep using the login function way too often.
  - IE: You login every 2min... instead of just keeping the bot running forever.
- If you are online 24h/7days a week. (which I doubt, since I'm running a bot 24/7 since forever without issue)

**Comment by YOLOP0wn** [comment]
i get banned from 2 servers with it, then i asked to gameforge the reason, and they told me that they see the known bot behaviour on their logs. (i used it to connect every 15min).

So i have developt my own with selenium, i am more limited but it does the job

**Comment by alaingilbert** [comment]
Are you on Discord ?
If yes add me ! (agilbert #2967)

**Pull request merged**
