### PR TITLE
Add language parameter to enable use of multiple servers with same name

### PR DESCRIPTION
**Pull request by magictucura**
- To enable using pyogame with users which have multiple accounts on
  server which are called the same. The language parameter enables to
explict set which server to use. If language is not set, the first in
the account list will be picked and the language will be set from the
information retrieved by the server.

allowed myself to use a try catch instead of the "hasattribute" 

see #62

### CODE REVIEW

**Comment by magictucura** [comment]
Rebased my stuff onto develop branch, switched base from master to develop

**Comment by PiecePaperCode** [comment]
thx
lobby system got updatet so i need to look if your code still works under the new lobby

**Comment by PiecePaperCode** [comment]
Ok it works after Lobby v3

**Comment by magictucura** [comment]
Ah nice, thank you very much:)

**Pull request merged**
