### PR TITLE
fix bugs and use builtin format function as PEP-3101 suggest

### PR DESCRIPTION
**Pull request by oalieno**
There is a bug in parse_int, '.' should be ','
Also, PEP-3101 suggest us to use builtin function format instead of %
Your API is awesome :smile:

### CODE REVIEW

**Comment by alaingilbert** [comment]
`parse_int` should really be a `.`
image
The function is used to parse the numbers that are formatted by ogame, and they uses a `.` for the thousands separator.

```
>>> int(u'3.091'.replace('.', '').strip())
3091
>>> int(u'3.091'.replace(',', '').strip())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: invalid literal for int() with base 10: '3.091'
```

Thank you ! I'm glad you like the library :)

**Comment by oalieno** [comment]
image
That's weird, our server display 3,425 instead of 3.425 O_O?
Maybe replace both to empty string?
```
u'3,425'.replace(',', '').replace('.', '').strip()
```

**Comment by alaingilbert** [comment]
That's what I thought !
What domain are you playing on ?
I'm on `en.ogame.gameforge.com`.

**Comment by oalieno** [comment]
I'm on `tw.ogame.gameforge.com`

**Comment by alaingilbert** [comment]
Ok, so I guess the right fix would be to verify which domain you uses, and change the "thousands separator" accordingly.

**Comment by oalieno** [comment]
But how do we know which server use ',' and which server use '.' ?
Maybe replace both to empty would be a easier solution? `replace(',', '').replace('.', '')`

**Comment by alaingilbert** [comment]
Since ogame never use any floating point numbers, that would actually work.

Otherwise, I was thinking about:
- Put a global variable `thousands_separator = '.'` [here](https://github.com/alaingilbert/pyogame/blob/master/ogame/__init__.py#L15)
- change [this](https://github.com/alaingilbert/pyogame/blob/master/ogame/__init__.py#L17) for `return int(text.replace(thousands_separator, '').strip())`
- [Here](https://github.com/alaingilbert/pyogame/blob/master/ogame/__init__.py#L112) you add a condition `if domain == 'domain_a': thousands_separator = ','`... (or create a function `thousands_separator = get_thousands_separator_for_domain(domain)`)
(something like that)

**Comment by oalieno** [comment]
OK, I understand~
So would you prefer I fix it by replacing both to empty string
or verify the domain and give it the right "thousands separator" to replace ?
I can do both.

**Comment by alaingilbert** [comment]
I guess we can go the easy way

**Comment by oalieno** [comment]
OK I update a new commit.
you can take a look at it :smiley:

**Pull request merged**
