### PR TITLE
fix no ships to fly

### PR DESCRIPTION
**Pull request by LAntoine**
If you tried to send a fleet while there was no ships, you would get an error because max(matches) could not be done.
In this case it will now return 0

### CODE REVIEW

**Comment by LAntoine** [comment]
it's also useful when trying to attack newbie

**Comment by alaingilbert** [comment]
I'm puzzled about the right way to do it.
Should we raise an exception if sending a fleet fails, or should we return `None`...
Returning 0 makes no sense to me though.
Anyway, can you make the Pull Request on the `develop` branch instead of `master` ?
Thanks for your awesome collaboration :)

ps: You should remove the parenthesis in the `if matches:`

**Comment by LAntoine** [comment]
You can raise an exception if you want, I didn't do it simply because I don't know how exceptions work in python.
But I would be interested in seeing how you implement it

**Comment by alaingilbert** [comment]
Thanks. I deployed it in the latest version (1.0.2)

**Pull request merged**
